/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "esp_hosted_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wifi_init_config, wifi_init_config, AUTO)


PB_BIND(wifi_country, wifi_country, AUTO)


PB_BIND(wifi_active_scan_time, wifi_active_scan_time, AUTO)


PB_BIND(wifi_scan_time, wifi_scan_time, AUTO)


PB_BIND(wifi_scan_channel_bitmap, wifi_scan_channel_bitmap, AUTO)


PB_BIND(wifi_scan_config, wifi_scan_config, AUTO)


PB_BIND(wifi_he_ap_info, wifi_he_ap_info, AUTO)


PB_BIND(wifi_ap_record, wifi_ap_record, AUTO)


PB_BIND(wifi_scan_threshold, wifi_scan_threshold, AUTO)


PB_BIND(wifi_pmf_config, wifi_pmf_config, AUTO)


PB_BIND(wifi_bss_max_idle_config, wifi_bss_max_idle_config, AUTO)


PB_BIND(wifi_ap_config, wifi_ap_config, AUTO)


PB_BIND(wifi_sta_config, wifi_sta_config, AUTO)


PB_BIND(wifi_config, wifi_config, AUTO)


PB_BIND(wifi_sta_info, wifi_sta_info, AUTO)


PB_BIND(wifi_sta_list, wifi_sta_list, AUTO)


PB_BIND(wifi_pkt_rx_ctrl, wifi_pkt_rx_ctrl, AUTO)


PB_BIND(wifi_promiscuous_pkt, wifi_promiscuous_pkt, AUTO)


PB_BIND(wifi_promiscuous_filter, wifi_promiscuous_filter, AUTO)


PB_BIND(wifi_csi_config, wifi_csi_config, AUTO)


PB_BIND(wifi_csi_info, wifi_csi_info, AUTO)


PB_BIND(wifi_ant_gpio, wifi_ant_gpio, AUTO)


PB_BIND(wifi_ant_gpio_config, wifi_ant_gpio_config, AUTO)


PB_BIND(wifi_ant_config, wifi_ant_config, AUTO)


PB_BIND(wifi_action_tx_req, wifi_action_tx_req, AUTO)


PB_BIND(wifi_ftm_initiator_cfg, wifi_ftm_initiator_cfg, AUTO)


PB_BIND(wifi_event_sta_scan_done, wifi_event_sta_scan_done, AUTO)


PB_BIND(wifi_event_sta_connected, wifi_event_sta_connected, AUTO)


PB_BIND(wifi_event_sta_disconnected, wifi_event_sta_disconnected, AUTO)


PB_BIND(wifi_event_sta_authmode_change, wifi_event_sta_authmode_change, AUTO)


PB_BIND(wifi_event_sta_wps_er_pin, wifi_event_sta_wps_er_pin, AUTO)


PB_BIND(ap_cred, ap_cred, AUTO)


PB_BIND(wifi_event_sta_wps_er_success, wifi_event_sta_wps_er_success, AUTO)


PB_BIND(wifi_event_ap_probe_req_rx, wifi_event_ap_probe_req_rx, AUTO)


PB_BIND(wifi_event_bss_rssi_low, wifi_event_bss_rssi_low, AUTO)


PB_BIND(wifi_ftm_report_entry, wifi_ftm_report_entry, AUTO)


PB_BIND(wifi_event_ftm_report, wifi_event_ftm_report, AUTO)


PB_BIND(wifi_event_action_tx_status, wifi_event_action_tx_status, AUTO)


PB_BIND(wifi_event_roc_done, wifi_event_roc_done, AUTO)


PB_BIND(wifi_event_ap_wps_rg_pin, wifi_event_ap_wps_rg_pin, AUTO)


PB_BIND(wifi_event_ap_wps_rg_fail_reason, wifi_event_ap_wps_rg_fail_reason, AUTO)


PB_BIND(wifi_event_ap_wps_rg_success, wifi_event_ap_wps_rg_success, AUTO)


PB_BIND(wifi_protocols, wifi_protocols, AUTO)


PB_BIND(wifi_bandwidths, wifi_bandwidths, AUTO)


PB_BIND(wifi_itwt_setup_config, wifi_itwt_setup_config, AUTO)


PB_BIND(wifi_twt_config, wifi_twt_config, AUTO)


PB_BIND(esp_app_desc, esp_app_desc, AUTO)


PB_BIND(ConnectedSTAList, ConnectedSTAList, AUTO)


PB_BIND(eap_fast_config, eap_fast_config, AUTO)


PB_BIND(Rpc_Req_GetMacAddress, Rpc_Req_GetMacAddress, AUTO)


PB_BIND(Rpc_Resp_GetMacAddress, Rpc_Resp_GetMacAddress, AUTO)


PB_BIND(Rpc_Req_GetMode, Rpc_Req_GetMode, AUTO)


PB_BIND(Rpc_Resp_GetMode, Rpc_Resp_GetMode, AUTO)


PB_BIND(Rpc_Req_SetMode, Rpc_Req_SetMode, AUTO)


PB_BIND(Rpc_Resp_SetMode, Rpc_Resp_SetMode, AUTO)


PB_BIND(Rpc_Req_GetPs, Rpc_Req_GetPs, AUTO)


PB_BIND(Rpc_Resp_GetPs, Rpc_Resp_GetPs, AUTO)


PB_BIND(Rpc_Req_SetPs, Rpc_Req_SetPs, AUTO)


PB_BIND(Rpc_Resp_SetPs, Rpc_Resp_SetPs, AUTO)


PB_BIND(Rpc_Req_SetMacAddress, Rpc_Req_SetMacAddress, AUTO)


PB_BIND(Rpc_Resp_SetMacAddress, Rpc_Resp_SetMacAddress, AUTO)


PB_BIND(Rpc_Req_OTABegin, Rpc_Req_OTABegin, AUTO)


PB_BIND(Rpc_Resp_OTABegin, Rpc_Resp_OTABegin, AUTO)


PB_BIND(Rpc_Req_OTAWrite, Rpc_Req_OTAWrite, AUTO)


PB_BIND(Rpc_Resp_OTAWrite, Rpc_Resp_OTAWrite, AUTO)


PB_BIND(Rpc_Req_OTAEnd, Rpc_Req_OTAEnd, AUTO)


PB_BIND(Rpc_Resp_OTAEnd, Rpc_Resp_OTAEnd, AUTO)


PB_BIND(Rpc_Req_OTAActivate, Rpc_Req_OTAActivate, AUTO)


PB_BIND(Rpc_Resp_OTAActivate, Rpc_Resp_OTAActivate, AUTO)


PB_BIND(Rpc_Req_AppGetDesc, Rpc_Req_AppGetDesc, AUTO)


PB_BIND(Rpc_Resp_AppGetDesc, Rpc_Resp_AppGetDesc, AUTO)


PB_BIND(Rpc_Req_WifiSetMaxTxPower, Rpc_Req_WifiSetMaxTxPower, AUTO)


PB_BIND(Rpc_Resp_WifiSetMaxTxPower, Rpc_Resp_WifiSetMaxTxPower, AUTO)


PB_BIND(Rpc_Req_WifiGetMaxTxPower, Rpc_Req_WifiGetMaxTxPower, AUTO)


PB_BIND(Rpc_Resp_WifiGetMaxTxPower, Rpc_Resp_WifiGetMaxTxPower, AUTO)


PB_BIND(Rpc_Req_ConfigHeartbeat, Rpc_Req_ConfigHeartbeat, AUTO)


PB_BIND(Rpc_Resp_ConfigHeartbeat, Rpc_Resp_ConfigHeartbeat, AUTO)


PB_BIND(Rpc_Req_WifiInit, Rpc_Req_WifiInit, AUTO)


PB_BIND(Rpc_Resp_WifiInit, Rpc_Resp_WifiInit, AUTO)


PB_BIND(Rpc_Req_WifiDeinit, Rpc_Req_WifiDeinit, AUTO)


PB_BIND(Rpc_Resp_WifiDeinit, Rpc_Resp_WifiDeinit, AUTO)


PB_BIND(Rpc_Req_WifiSetConfig, Rpc_Req_WifiSetConfig, AUTO)


PB_BIND(Rpc_Resp_WifiSetConfig, Rpc_Resp_WifiSetConfig, AUTO)


PB_BIND(Rpc_Req_WifiGetConfig, Rpc_Req_WifiGetConfig, AUTO)


PB_BIND(Rpc_Resp_WifiGetConfig, Rpc_Resp_WifiGetConfig, AUTO)


PB_BIND(Rpc_Req_WifiConnect, Rpc_Req_WifiConnect, AUTO)


PB_BIND(Rpc_Resp_WifiConnect, Rpc_Resp_WifiConnect, AUTO)


PB_BIND(Rpc_Req_WifiDisconnect, Rpc_Req_WifiDisconnect, AUTO)


PB_BIND(Rpc_Resp_WifiDisconnect, Rpc_Resp_WifiDisconnect, AUTO)


PB_BIND(Rpc_Req_WifiStart, Rpc_Req_WifiStart, AUTO)


PB_BIND(Rpc_Resp_WifiStart, Rpc_Resp_WifiStart, AUTO)


PB_BIND(Rpc_Req_WifiStop, Rpc_Req_WifiStop, AUTO)


PB_BIND(Rpc_Resp_WifiStop, Rpc_Resp_WifiStop, AUTO)


PB_BIND(Rpc_Req_WifiScanStart, Rpc_Req_WifiScanStart, AUTO)


PB_BIND(Rpc_Resp_WifiScanStart, Rpc_Resp_WifiScanStart, AUTO)


PB_BIND(Rpc_Req_WifiScanStop, Rpc_Req_WifiScanStop, AUTO)


PB_BIND(Rpc_Resp_WifiScanStop, Rpc_Resp_WifiScanStop, AUTO)


PB_BIND(Rpc_Req_WifiScanGetApNum, Rpc_Req_WifiScanGetApNum, AUTO)


PB_BIND(Rpc_Resp_WifiScanGetApNum, Rpc_Resp_WifiScanGetApNum, AUTO)


PB_BIND(Rpc_Req_WifiScanGetApRecords, Rpc_Req_WifiScanGetApRecords, AUTO)


PB_BIND(Rpc_Resp_WifiScanGetApRecords, Rpc_Resp_WifiScanGetApRecords, AUTO)


PB_BIND(Rpc_Req_WifiScanGetApRecord, Rpc_Req_WifiScanGetApRecord, AUTO)


PB_BIND(Rpc_Resp_WifiScanGetApRecord, Rpc_Resp_WifiScanGetApRecord, AUTO)


PB_BIND(Rpc_Req_WifiClearApList, Rpc_Req_WifiClearApList, AUTO)


PB_BIND(Rpc_Resp_WifiClearApList, Rpc_Resp_WifiClearApList, AUTO)


PB_BIND(Rpc_Req_WifiRestore, Rpc_Req_WifiRestore, AUTO)


PB_BIND(Rpc_Resp_WifiRestore, Rpc_Resp_WifiRestore, AUTO)


PB_BIND(Rpc_Req_WifiClearFastConnect, Rpc_Req_WifiClearFastConnect, AUTO)


PB_BIND(Rpc_Resp_WifiClearFastConnect, Rpc_Resp_WifiClearFastConnect, AUTO)


PB_BIND(Rpc_Req_WifiDeauthSta, Rpc_Req_WifiDeauthSta, AUTO)


PB_BIND(Rpc_Resp_WifiDeauthSta, Rpc_Resp_WifiDeauthSta, AUTO)


PB_BIND(Rpc_Req_WifiStaGetApInfo, Rpc_Req_WifiStaGetApInfo, AUTO)


PB_BIND(Rpc_Resp_WifiStaGetApInfo, Rpc_Resp_WifiStaGetApInfo, AUTO)


PB_BIND(Rpc_Req_WifiSetProtocol, Rpc_Req_WifiSetProtocol, AUTO)


PB_BIND(Rpc_Resp_WifiSetProtocol, Rpc_Resp_WifiSetProtocol, AUTO)


PB_BIND(Rpc_Req_WifiGetProtocol, Rpc_Req_WifiGetProtocol, AUTO)


PB_BIND(Rpc_Resp_WifiGetProtocol, Rpc_Resp_WifiGetProtocol, AUTO)


PB_BIND(Rpc_Req_WifiSetBandwidth, Rpc_Req_WifiSetBandwidth, AUTO)


PB_BIND(Rpc_Resp_WifiSetBandwidth, Rpc_Resp_WifiSetBandwidth, AUTO)


PB_BIND(Rpc_Req_WifiGetBandwidth, Rpc_Req_WifiGetBandwidth, AUTO)


PB_BIND(Rpc_Resp_WifiGetBandwidth, Rpc_Resp_WifiGetBandwidth, AUTO)


PB_BIND(Rpc_Req_WifiSetChannel, Rpc_Req_WifiSetChannel, AUTO)


PB_BIND(Rpc_Resp_WifiSetChannel, Rpc_Resp_WifiSetChannel, AUTO)


PB_BIND(Rpc_Req_WifiGetChannel, Rpc_Req_WifiGetChannel, AUTO)


PB_BIND(Rpc_Resp_WifiGetChannel, Rpc_Resp_WifiGetChannel, AUTO)


PB_BIND(Rpc_Req_WifiSetStorage, Rpc_Req_WifiSetStorage, AUTO)


PB_BIND(Rpc_Resp_WifiSetStorage, Rpc_Resp_WifiSetStorage, AUTO)


PB_BIND(Rpc_Req_WifiSetCountryCode, Rpc_Req_WifiSetCountryCode, AUTO)


PB_BIND(Rpc_Resp_WifiSetCountryCode, Rpc_Resp_WifiSetCountryCode, AUTO)


PB_BIND(Rpc_Req_WifiGetCountryCode, Rpc_Req_WifiGetCountryCode, AUTO)


PB_BIND(Rpc_Resp_WifiGetCountryCode, Rpc_Resp_WifiGetCountryCode, AUTO)


PB_BIND(Rpc_Req_WifiSetCountry, Rpc_Req_WifiSetCountry, AUTO)


PB_BIND(Rpc_Resp_WifiSetCountry, Rpc_Resp_WifiSetCountry, AUTO)


PB_BIND(Rpc_Req_WifiGetCountry, Rpc_Req_WifiGetCountry, AUTO)


PB_BIND(Rpc_Resp_WifiGetCountry, Rpc_Resp_WifiGetCountry, AUTO)


PB_BIND(Rpc_Req_WifiApGetStaList, Rpc_Req_WifiApGetStaList, AUTO)


PB_BIND(Rpc_Resp_WifiApGetStaList, Rpc_Resp_WifiApGetStaList, AUTO)


PB_BIND(Rpc_Req_WifiApGetStaAid, Rpc_Req_WifiApGetStaAid, AUTO)


PB_BIND(Rpc_Req_WifiStaGetNegotiatedPhymode, Rpc_Req_WifiStaGetNegotiatedPhymode, AUTO)


PB_BIND(Rpc_Resp_WifiStaGetNegotiatedPhymode, Rpc_Resp_WifiStaGetNegotiatedPhymode, AUTO)


PB_BIND(Rpc_Resp_WifiApGetStaAid, Rpc_Resp_WifiApGetStaAid, AUTO)


PB_BIND(Rpc_Req_WifiStaGetRssi, Rpc_Req_WifiStaGetRssi, AUTO)


PB_BIND(Rpc_Resp_WifiStaGetRssi, Rpc_Resp_WifiStaGetRssi, AUTO)


PB_BIND(Rpc_Req_WifiStaGetAid, Rpc_Req_WifiStaGetAid, AUTO)


PB_BIND(Rpc_Resp_WifiStaGetAid, Rpc_Resp_WifiStaGetAid, AUTO)


PB_BIND(Rpc_Req_WifiSetProtocols, Rpc_Req_WifiSetProtocols, AUTO)


PB_BIND(Rpc_Resp_WifiSetProtocols, Rpc_Resp_WifiSetProtocols, AUTO)


PB_BIND(Rpc_Req_WifiGetProtocols, Rpc_Req_WifiGetProtocols, AUTO)


PB_BIND(Rpc_Resp_WifiGetProtocols, Rpc_Resp_WifiGetProtocols, AUTO)


PB_BIND(Rpc_Req_WifiSetBandwidths, Rpc_Req_WifiSetBandwidths, AUTO)


PB_BIND(Rpc_Resp_WifiSetBandwidths, Rpc_Resp_WifiSetBandwidths, AUTO)


PB_BIND(Rpc_Req_WifiGetBandwidths, Rpc_Req_WifiGetBandwidths, AUTO)


PB_BIND(Rpc_Resp_WifiGetBandwidths, Rpc_Resp_WifiGetBandwidths, AUTO)


PB_BIND(Rpc_Req_WifiSetBand, Rpc_Req_WifiSetBand, AUTO)


PB_BIND(Rpc_Resp_WifiSetBand, Rpc_Resp_WifiSetBand, AUTO)


PB_BIND(Rpc_Req_WifiGetBand, Rpc_Req_WifiGetBand, AUTO)


PB_BIND(Rpc_Resp_WifiGetBand, Rpc_Resp_WifiGetBand, AUTO)


PB_BIND(Rpc_Req_WifiSetBandMode, Rpc_Req_WifiSetBandMode, AUTO)


PB_BIND(Rpc_Resp_WifiSetBandMode, Rpc_Resp_WifiSetBandMode, AUTO)


PB_BIND(Rpc_Req_WifiGetBandMode, Rpc_Req_WifiGetBandMode, AUTO)


PB_BIND(Rpc_Resp_WifiGetBandMode, Rpc_Resp_WifiGetBandMode, AUTO)


PB_BIND(Rpc_Req_WifiSetInactiveTime, Rpc_Req_WifiSetInactiveTime, AUTO)


PB_BIND(Rpc_Resp_WifiSetInactiveTime, Rpc_Resp_WifiSetInactiveTime, AUTO)


PB_BIND(Rpc_Req_WifiGetInactiveTime, Rpc_Req_WifiGetInactiveTime, AUTO)


PB_BIND(Rpc_Resp_WifiGetInactiveTime, Rpc_Resp_WifiGetInactiveTime, AUTO)


PB_BIND(Rpc_Req_WifiStaItwtSetup, Rpc_Req_WifiStaItwtSetup, AUTO)


PB_BIND(Rpc_Resp_WifiStaItwtSetup, Rpc_Resp_WifiStaItwtSetup, AUTO)


PB_BIND(Rpc_Req_WifiStaItwtTeardown, Rpc_Req_WifiStaItwtTeardown, AUTO)


PB_BIND(Rpc_Resp_WifiStaItwtTeardown, Rpc_Resp_WifiStaItwtTeardown, AUTO)


PB_BIND(Rpc_Req_WifiStaItwtSuspend, Rpc_Req_WifiStaItwtSuspend, AUTO)


PB_BIND(Rpc_Resp_WifiStaItwtSuspend, Rpc_Resp_WifiStaItwtSuspend, AUTO)


PB_BIND(Rpc_Req_WifiStaItwtGetFlowIdStatus, Rpc_Req_WifiStaItwtGetFlowIdStatus, AUTO)


PB_BIND(Rpc_Resp_WifiStaItwtGetFlowIdStatus, Rpc_Resp_WifiStaItwtGetFlowIdStatus, AUTO)


PB_BIND(Rpc_Req_WifiStaItwtSendProbeReq, Rpc_Req_WifiStaItwtSendProbeReq, AUTO)


PB_BIND(Rpc_Resp_WifiStaItwtSendProbeReq, Rpc_Resp_WifiStaItwtSendProbeReq, AUTO)


PB_BIND(Rpc_Req_WifiStaItwtSetTargetWakeTimeOffset, Rpc_Req_WifiStaItwtSetTargetWakeTimeOffset, AUTO)


PB_BIND(Rpc_Resp_WifiStaItwtSetTargetWakeTimeOffset, Rpc_Resp_WifiStaItwtSetTargetWakeTimeOffset, AUTO)


PB_BIND(Rpc_Req_WifiStaTwtConfig, Rpc_Req_WifiStaTwtConfig, AUTO)


PB_BIND(Rpc_Resp_WifiStaTwtConfig, Rpc_Resp_WifiStaTwtConfig, AUTO)


PB_BIND(Rpc_Req_GetCoprocessorFwVersion, Rpc_Req_GetCoprocessorFwVersion, AUTO)


PB_BIND(Rpc_Resp_GetCoprocessorFwVersion, Rpc_Resp_GetCoprocessorFwVersion, AUTO)


PB_BIND(Rpc_Req_SetDhcpDnsStatus, Rpc_Req_SetDhcpDnsStatus, AUTO)


PB_BIND(Rpc_Resp_SetDhcpDnsStatus, Rpc_Resp_SetDhcpDnsStatus, AUTO)


PB_BIND(Rpc_Req_GetDhcpDnsStatus, Rpc_Req_GetDhcpDnsStatus, AUTO)


PB_BIND(Rpc_Resp_GetDhcpDnsStatus, Rpc_Resp_GetDhcpDnsStatus, AUTO)


PB_BIND(Rpc_Req_SuppDppInit, Rpc_Req_SuppDppInit, AUTO)


PB_BIND(Rpc_Resp_SuppDppInit, Rpc_Resp_SuppDppInit, AUTO)


PB_BIND(Rpc_Req_SuppDppDeinit, Rpc_Req_SuppDppDeinit, AUTO)


PB_BIND(Rpc_Resp_SuppDppDeinit, Rpc_Resp_SuppDppDeinit, AUTO)


PB_BIND(Rpc_Req_SuppDppBootstrapGen, Rpc_Req_SuppDppBootstrapGen, AUTO)


PB_BIND(Rpc_Resp_SuppDppBootstrapGen, Rpc_Resp_SuppDppBootstrapGen, AUTO)


PB_BIND(Rpc_Req_SuppDppStartListen, Rpc_Req_SuppDppStartListen, AUTO)


PB_BIND(Rpc_Resp_SuppDppStartListen, Rpc_Resp_SuppDppStartListen, AUTO)


PB_BIND(Rpc_Req_SuppDppStopListen, Rpc_Req_SuppDppStopListen, AUTO)


PB_BIND(Rpc_Resp_SuppDppStopListen, Rpc_Resp_SuppDppStopListen, AUTO)


PB_BIND(Rpc_Req_IfaceMacAddrSetGet, Rpc_Req_IfaceMacAddrSetGet, AUTO)


PB_BIND(Rpc_Resp_IfaceMacAddrSetGet, Rpc_Resp_IfaceMacAddrSetGet, AUTO)


PB_BIND(Rpc_Req_IfaceMacAddrLenGet, Rpc_Req_IfaceMacAddrLenGet, AUTO)


PB_BIND(Rpc_Resp_IfaceMacAddrLenGet, Rpc_Resp_IfaceMacAddrLenGet, AUTO)


PB_BIND(Rpc_Req_FeatureControl, Rpc_Req_FeatureControl, AUTO)


PB_BIND(Rpc_Resp_FeatureControl, Rpc_Resp_FeatureControl, AUTO)


PB_BIND(Rpc_Event_WifiEventNoArgs, Rpc_Event_WifiEventNoArgs, AUTO)


PB_BIND(Rpc_Event_ESPInit, Rpc_Event_ESPInit, AUTO)


PB_BIND(Rpc_Event_Heartbeat, Rpc_Event_Heartbeat, AUTO)


PB_BIND(Rpc_Event_AP_StaDisconnected, Rpc_Event_AP_StaDisconnected, AUTO)


PB_BIND(Rpc_Event_AP_StaConnected, Rpc_Event_AP_StaConnected, AUTO)


PB_BIND(Rpc_Event_StaScanDone, Rpc_Event_StaScanDone, AUTO)


PB_BIND(Rpc_Event_StaConnected, Rpc_Event_StaConnected, AUTO)


PB_BIND(Rpc_Event_StaDisconnected, Rpc_Event_StaDisconnected, AUTO)


PB_BIND(Rpc_GpioConfig, Rpc_GpioConfig, AUTO)


PB_BIND(Rpc_Req_GpioConfig, Rpc_Req_GpioConfig, AUTO)


PB_BIND(Rpc_Resp_GpioConfig, Rpc_Resp_GpioConfig, AUTO)


PB_BIND(Rpc_Req_GpioResetPin, Rpc_Req_GpioResetPin, AUTO)


PB_BIND(Rpc_Resp_GpioResetPin, Rpc_Resp_GpioResetPin, AUTO)


PB_BIND(Rpc_Req_GpioSetLevel, Rpc_Req_GpioSetLevel, AUTO)


PB_BIND(Rpc_Resp_GpioSetLevel, Rpc_Resp_GpioSetLevel, AUTO)


PB_BIND(Rpc_Req_GpioGetLevel, Rpc_Req_GpioGetLevel, AUTO)


PB_BIND(Rpc_Resp_GpioGetLevel, Rpc_Resp_GpioGetLevel, AUTO)


PB_BIND(Rpc_Req_GpioSetDirection, Rpc_Req_GpioSetDirection, AUTO)


PB_BIND(Rpc_Resp_GpioSetDirection, Rpc_Resp_GpioSetDirection, AUTO)


PB_BIND(Rpc_Req_GpioInputEnable, Rpc_Req_GpioInputEnable, AUTO)


PB_BIND(Rpc_Resp_GpioInputEnable, Rpc_Resp_GpioInputEnable, AUTO)


PB_BIND(Rpc_Req_GpioSetPullMode, Rpc_Req_GpioSetPullMode, AUTO)


PB_BIND(Rpc_Resp_GpioSetPullMode, Rpc_Resp_GpioSetPullMode, AUTO)


PB_BIND(Rpc_Event_DhcpDnsStatus, Rpc_Event_DhcpDnsStatus, AUTO)


PB_BIND(Rpc_Event_StaItwtSetup, Rpc_Event_StaItwtSetup, AUTO)


PB_BIND(Rpc_Event_StaItwtTeardown, Rpc_Event_StaItwtTeardown, AUTO)


PB_BIND(Rpc_Event_StaItwtSuspend, Rpc_Event_StaItwtSuspend, AUTO)


PB_BIND(Rpc_Event_StaItwtProbe, Rpc_Event_StaItwtProbe, AUTO)


PB_BIND(Rpc_Req_WifiStaEnterpriseEnable, Rpc_Req_WifiStaEnterpriseEnable, AUTO)


PB_BIND(Rpc_Resp_WifiStaEnterpriseEnable, Rpc_Resp_WifiStaEnterpriseEnable, AUTO)


PB_BIND(Rpc_Req_WifiStaEnterpriseDisable, Rpc_Req_WifiStaEnterpriseDisable, AUTO)


PB_BIND(Rpc_Resp_WifiStaEnterpriseDisable, Rpc_Resp_WifiStaEnterpriseDisable, AUTO)


PB_BIND(Rpc_Req_EapSetIdentity, Rpc_Req_EapSetIdentity, AUTO)


PB_BIND(Rpc_Resp_EapSetIdentity, Rpc_Resp_EapSetIdentity, AUTO)


PB_BIND(Rpc_Req_EapClearIdentity, Rpc_Req_EapClearIdentity, AUTO)


PB_BIND(Rpc_Resp_EapClearIdentity, Rpc_Resp_EapClearIdentity, AUTO)


PB_BIND(Rpc_Req_EapSetUsername, Rpc_Req_EapSetUsername, AUTO)


PB_BIND(Rpc_Resp_EapSetUsername, Rpc_Resp_EapSetUsername, AUTO)


PB_BIND(Rpc_Req_EapClearUsername, Rpc_Req_EapClearUsername, AUTO)


PB_BIND(Rpc_Resp_EapClearUsername, Rpc_Resp_EapClearUsername, AUTO)


PB_BIND(Rpc_Req_EapSetPassword, Rpc_Req_EapSetPassword, AUTO)


PB_BIND(Rpc_Resp_EapSetPassword, Rpc_Resp_EapSetPassword, AUTO)


PB_BIND(Rpc_Req_EapClearPassword, Rpc_Req_EapClearPassword, AUTO)


PB_BIND(Rpc_Resp_EapClearPassword, Rpc_Resp_EapClearPassword, AUTO)


PB_BIND(Rpc_Req_EapSetNewPassword, Rpc_Req_EapSetNewPassword, AUTO)


PB_BIND(Rpc_Resp_EapSetNewPassword, Rpc_Resp_EapSetNewPassword, AUTO)


PB_BIND(Rpc_Req_EapClearNewPassword, Rpc_Req_EapClearNewPassword, AUTO)


PB_BIND(Rpc_Resp_EapClearNewPassword, Rpc_Resp_EapClearNewPassword, AUTO)


PB_BIND(Rpc_Req_EapSetCaCert, Rpc_Req_EapSetCaCert, AUTO)


PB_BIND(Rpc_Resp_EapSetCaCert, Rpc_Resp_EapSetCaCert, AUTO)


PB_BIND(Rpc_Req_EapClearCaCert, Rpc_Req_EapClearCaCert, AUTO)


PB_BIND(Rpc_Resp_EapClearCaCert, Rpc_Resp_EapClearCaCert, AUTO)


PB_BIND(Rpc_Req_EapSetCertificateAndKey, Rpc_Req_EapSetCertificateAndKey, AUTO)


PB_BIND(Rpc_Resp_EapSetCertificateAndKey, Rpc_Resp_EapSetCertificateAndKey, AUTO)


PB_BIND(Rpc_Req_EapClearCertificateAndKey, Rpc_Req_EapClearCertificateAndKey, AUTO)


PB_BIND(Rpc_Resp_EapClearCertificateAndKey, Rpc_Resp_EapClearCertificateAndKey, AUTO)


PB_BIND(Rpc_Req_EapSetDisableTimeCheck, Rpc_Req_EapSetDisableTimeCheck, AUTO)


PB_BIND(Rpc_Resp_EapSetDisableTimeCheck, Rpc_Resp_EapSetDisableTimeCheck, AUTO)


PB_BIND(Rpc_Req_EapGetDisableTimeCheck, Rpc_Req_EapGetDisableTimeCheck, AUTO)


PB_BIND(Rpc_Resp_EapGetDisableTimeCheck, Rpc_Resp_EapGetDisableTimeCheck, AUTO)


PB_BIND(Rpc_Req_EapSetTtlsPhase2Method, Rpc_Req_EapSetTtlsPhase2Method, AUTO)


PB_BIND(Rpc_Resp_EapSetTtlsPhase2Method, Rpc_Resp_EapSetTtlsPhase2Method, AUTO)


PB_BIND(Rpc_Req_EapSetSuiteb192bitCertification, Rpc_Req_EapSetSuiteb192bitCertification, AUTO)


PB_BIND(Rpc_Resp_EapSetSuiteb192bitCertification, Rpc_Resp_EapSetSuiteb192bitCertification, AUTO)


PB_BIND(Rpc_Req_EapSetPacFile, Rpc_Req_EapSetPacFile, AUTO)


PB_BIND(Rpc_Resp_EapSetPacFile, Rpc_Resp_EapSetPacFile, AUTO)


PB_BIND(Rpc_Req_EapSetFastParams, Rpc_Req_EapSetFastParams, AUTO)


PB_BIND(Rpc_Resp_EapSetFastParams, Rpc_Resp_EapSetFastParams, AUTO)


PB_BIND(Rpc_Req_EapUseDefaultCertBundle, Rpc_Req_EapUseDefaultCertBundle, AUTO)


PB_BIND(Rpc_Resp_EapUseDefaultCertBundle, Rpc_Resp_EapUseDefaultCertBundle, AUTO)


PB_BIND(Rpc_Req_WifiSetOkcSupport, Rpc_Req_WifiSetOkcSupport, AUTO)


PB_BIND(Rpc_Resp_WifiSetOkcSupport, Rpc_Resp_WifiSetOkcSupport, AUTO)


PB_BIND(Rpc_Req_EapSetDomainName, Rpc_Req_EapSetDomainName, AUTO)


PB_BIND(Rpc_Resp_EapSetDomainName, Rpc_Resp_EapSetDomainName, AUTO)


PB_BIND(Rpc_Req_EapSetEapMethods, Rpc_Req_EapSetEapMethods, AUTO)


PB_BIND(Rpc_Resp_EapSetEapMethods, Rpc_Resp_EapSetEapMethods, AUTO)


PB_BIND(Rpc_Event_SuppDppUriReady, Rpc_Event_SuppDppUriReady, AUTO)


PB_BIND(Rpc_Event_SuppDppCfgRecvd, Rpc_Event_SuppDppCfgRecvd, AUTO)


PB_BIND(Rpc_Event_SuppDppFail, Rpc_Event_SuppDppFail, AUTO)


PB_BIND(Rpc_Event_WifiDppUriReady, Rpc_Event_WifiDppUriReady, AUTO)


PB_BIND(Rpc_Event_WifiDppCfgRecvd, Rpc_Event_WifiDppCfgRecvd, AUTO)


PB_BIND(Rpc_Event_WifiDppFail, Rpc_Event_WifiDppFail, AUTO)


PB_BIND(Rpc_Req_CustomRpc, Rpc_Req_CustomRpc, AUTO)


PB_BIND(Rpc_Resp_CustomRpc, Rpc_Resp_CustomRpc, AUTO)


PB_BIND(Rpc_Event_CustomRpc, Rpc_Event_CustomRpc, AUTO)


PB_BIND(Rpc, Rpc, 2)

























